"""job migration

Revision ID: 1a11c4121b14
Revises: 5396b7b2132d
Create Date: 2024-08-27 11:04:31.111837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import String
# revision identifiers, used by Alembic.
revision = '1a11c4121b14'
down_revision = '5396b7b2132d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', postgresql.ARRAY(String()), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('skills')

    # ### end Alembic commands ###
